import type { Metadata } from "next";
import "./globals.css";
import Header from "@/components/header";
import BackgroundImage from "@/components/backgroundImage";
import localFont from "next/font/local";
import Footer from "@/components/footer";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const suitFont = localFont({
  src: [
    {
      path: "../public/fonts/SUIT-Bold.otf",
      weight: "700",
      style: "normal",
    },
    {
      path: "../public/fonts/SUIT-Regular.otf",
      weight: "400",
      style: "normal",
    },
    {
      path: "../public/fonts/SUIT-Light.otf",
      weight: "300",
      style: "normal",
    },
    {
      path: "../public/fonts/SUIT-Medium.otf",
      weight: "500",
      style: "normal",
    },
    {
      path: "../public/fonts/SUIT-SemiBold.otf",
      weight: "600",
      style: "normal",
    },
    {
      path: "../public/fonts/SUIT-ExtraBold.otf",
      weight: "800",
      style: "normal",
    },
    {
      path: "../public/fonts/SUIT-ExtraLight.otf",
      weight: "200",
      style: "normal",
    },
    {
      path: "../public/fonts/SUIT-Thin.otf",
      weight: "100",
      style: "normal",
    },
    {
      path: "../public/fonts/SUIT-Heavy.otf",
      weight: "900",
      style: "normal",
    },
  ],
});

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" className={suitFont.className}>
      <body className="mx-auto">
        <BackgroundImage />
        <Header />
        <main className="md:mt-[111px] min-h-screen max-w-pc mx-auto">
          {children}
        </main>
        <Footer />
      </body>
    </html>
  );
}
